mangosthree/server

CMakeLists.txt
src/game/Server/DB2Stores.h
src/modules/SD2/CMakeLists.txt
src/shared/DataStores/DB2FileLoader.h
src/shared/DataStores/DBCFileLoader.h

Corrected case sensitive library name and slash path for unix
compatibility

Correction for unix

---

src/game/Object/Object.h
src/game/Object/Unit.cpp
src/game/Object/Unit.h

Fixed:
22 errors
19 warnings
82 errors and 7 warnings remaining, at this point.

Some build errors and warning fixed

---

src/game/Object/Player.h
src/game/Server/Opcodes.cpp
src/game/Server/Opcodes.h
src/game/Server/SharedDefines.h

72 errors and 7 warnings remaining at this point

Some build errors fixed

---

src/game/BattleGround/BattleGroundHandler.cpp
src/game/Object/AggressorAI.cpp
src/game/Object/Creature.cpp
src/game/Object/Creature.h
src/game/Object/CreatureAISelector.cpp
src/game/Object/PetAI.cpp
src/game/Object/Player.h
src/game/Object/Unit.cpp
src/game/Object/Unit.h
src/game/Server/WorldSession.h
src/game/WorldHandlers/GridNotifiers.h
src/game/WorldHandlers/GuildHandler.cpp
src/game/WorldHandlers/NPCHandler.cpp
src/game/WorldHandlers/PetHandler.cpp
src/game/WorldHandlers/Spell.cpp
src/game/WorldHandlers/TaxiHandler.cpp
src/modules/Eluna/PlayerMethods.h
src/modules/Eluna/UnitMethods.h

Build error fixes

---

src/game/Object/Creature.cpp
src/game/Object/Creature.h
src/game/Object/ObjectMgr.cpp
src/game/Object/ObjectMgr.h
src/game/Object/Unit.cpp
src/game/Server/DBCStructure.h
src/game/WorldHandlers/Chat.cpp

A few build fixes made.
Tabs converted into spaces, although it does not seem to show that in
the list of changes!

Build fixes made and tabs turned  into spaces

---

src/game/Object/Creature.cpp

Function added back

---

src/game/Object/LootMgr.h
src/game/Object/SpellMgr.cpp
src/game/Object/Unit.cpp
src/game/WorldHandlers/Map.cpp
src/game/WorldHandlers/Map.h
src/game/WorldHandlers/Spell.h
src/game/WorldHandlers/Weather.cpp
src/game/WorldHandlers/Weather.h

Build errors and warnings fixes
Spell class - Fix for inaccessible class data.
Accessor functions created for protected member, m_selfContainer

Build errors and warnings fixes

---

src/game/Object/Creature.h
src/game/Object/GameObject.h
src/game/Object/Guild.cpp
src/game/Object/Object.cpp
src/game/Object/ObjectMgr.h
src/game/Server/DBCStructure.h

5 errors remaining at this point.
The only warnings left are in the Stormlib library.

More build errors and warnings fixed

---

src/game/Server/DBCStructure.h
src/modules/Eluna/UnitMethods.h
src/shared/Utilities/Util.cpp
src/shared/Utilities/Util.h

3 errors left!
Then the <bleep> will really hit the fan!

And more build errors fixed

---

src/game/BattleGround/BattleGround.h
src/game/Object/Player.cpp
src/game/Object/Player.h
src/modules/Eluna/UnitMethods.h

A few more build error fixes

---

src/game/BattleGround/BattleGround.h
src/game/BattleGround/BattleGroundMgr.cpp
src/game/BattleGround/BattleGroundMgr.h
src/game/ChatCommands/Level3.cpp
src/game/Object/ArenaTeam.cpp
src/game/Object/ArenaTeam.h
src/game/Object/Creature.h
src/game/Object/ObjectMgr.cpp
src/game/Object/ObjectMgr.h
src/game/Object/Player.cpp
src/game/Object/Player.h
src/game/Object/UpdateFields.h
src/game/Server/DBCStructure.h
src/game/Server/SQLStorages.cpp
src/game/Server/SQLStorages.h
src/game/Server/SharedDefines.h
src/game/Tools/Language.h
src/game/WorldHandlers/Map.cpp
src/game/WorldHandlers/Map.h
src/game/WorldHandlers/QuestHandler.cpp
src/game/WorldHandlers/ScriptMgr.cpp
src/game/WorldHandlers/ScriptMgr.h
src/game/WorldHandlers/Weather.cpp
src/game/WorldHandlers/Weather.h
src/game/WorldHandlers/World.cpp
src/game/WorldHandlers/World.h
src/modules/Eluna/PlayerMethods.h
src/modules/SD2/system/ScriptDevMgr.cpp

Weather system changed to that of the previous cores.
This is part of the current build error fixes.

Weather system changed to that of the previous cores.

---

src/game/Object/ObjectMgr.h
src/game/Server/DBCStores.h
src/game/Server/DBCStructure.h
src/game/Server/WorldSession.h
src/game/WorldHandlers/Group.h
src/game/WorldHandlers/LFGHandler.cpp
src/game/WorldHandlers/LFGMgr.cpp
src/game/WorldHandlers/LFGMgr.h
src/game/WorldHandlers/World.cpp
src/game/WorldHandlers/World.h

LFGMgr.cpp and LFGMgr.h added to Three.
This is part of the current build error fixes.

LFGMgr.cpp and LFGMgr.h added to Three

---

src/tools/map-extractor/loadlib/loadlib.h

Corrected path to Stormlib.h

---

src/game/Server/DBCStores.cpp
src/game/Server/DBCStores.h
src/game/Server/DBCStructure.h

Case-insensitive channel name comparison for "world".
commit 43860fb on cabfever's repo

(Author: Olion17) Server-owned world channel

---

src/tools/genrevision/genrevision.cpp

Included file stdlib.h added
Errors still exist in the build. 
PR'ing this as a test to see if remaining errors are due to an incompatible compiler.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangosthree/server/63)

Linux build error fix

---

src/tools/vmap-extractor/vmapexport.cpp

VMAP file creation:
The check for the "Buildings" folder code is now the same as the previous
cores.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangosthree/server/66)

VMAP - Check for Buildings folder

---

src/tools/Extractor_Binaries/ExtractResources.sh
src/tools/Extractor_projects/shared/ExtractorCommon.cpp
src/tools/Extractor_projects/shared/ExtractorCommon.h
src/tools/Extractor_projects/vmap-assembler/vmap_assembler.cpp
src/tools/Extractor_projects/vmap-extractor/vmapexport.cpp

It now appears to work. It is difficult to know if the resulting files
are correct, without a running server.
MMAP extraction not tested at this point in time, but it did not work
prior to this fix for VMAP creation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangosthree/server/68)

VMAP creation fixed - files are now created

---

src/game/Server/DBCStores.cpp
src/game/Server/DBCStores.h
src/game/Server/DBCStructure.h

DO NOT MERGE
This is a test to see if it gets tripped up by Travis during the Linux
build.
If all okay, then this can be merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangosthree/server/70)

ChatChannels fix - test PR

---

src/game/WorldHandlers/World.cpp

The core was not loading the DB2 files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangosthree/server/74)

Added missing call to LoadDB2Stores( )

---

src/modules/SD3/scripts/eastern_kingdoms/blackrock_mountain/molten_core/molten_core.cpp
src/modules/SD3/scripts/outland/netherstorm.cpp
src/modules/SD3/scripts/outland/shadowmoon_valley.cpp

Scripts set up to work for Cata
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangosthree/server/77)

Scripts set up to work for Cata

---

src/game/WorldHandlers/World.cpp
src/mangosd/mangosd.conf.dist.in

Missing code related to Warden added
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangosthree/server/78)

Missing code related to Warden added

---

src/game/Server/WorldSession.cpp

Code commented out to prevent crash on login.
This will be addressed as soon as possible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangosthree/server/79)

Warden issue - disabled to prevent crash

---

src/game/Server/SQLStorages.cpp

Correct format string now in place for the creature_template table
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangosthree/server/83)

creature_template table's format string corrected

---

src/game/Object/ObjectMgr.cpp

Server start up error fixes
Misnaming of the creature_template table's column.
Change to how the check is made on the creature_template table's
UnitClass column.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangosthree/server/88)

Server start up error fixes

---

src/game/ChatCommands/Level3.cpp
src/game/Object/Object.cpp
src/game/Object/Object.h
src/game/Object/Player.cpp
src/game/Server/SharedDefines.h
src/game/WorldHandlers/Map.cpp
src/game/WorldHandlers/Weather.cpp
src/game/WorldHandlers/Weather.h
src/game/WorldHandlers/World.cpp
src/game/WorldHandlers/World.h
src/modules/Eluna/MapMethods.h
src/shared/revision.h

Fixed by implementing the cmangos Cata commit
[c13018] Improve Weather handling
and comparing their code with the current system.
Thanks,. cmangos :-)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangosthree/server/92)

Weather system fixed

---

src/game/Object/Player.cpp
src/game/Object/Player.h
src/game/WorldHandlers/World.cpp
src/game/WorldHandlers/World.h

Code related to the non-existent table, character_battleground_random
removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangosthree/server/97)

Unused code removed (related to character_battleground_random table)

---

src/tools/Extractor_projects/Movemap-Generator/CMakeLists.txt
src/tools/Extractor_projects/vmap-assembler/CMakeLists.txt

sorry, my last commit overwrote it 
*hides*
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangosthree/server/98)

Overwritten CMakeLists entries put back

---

src/game/BattleGround/BattleGround.cpp
src/game/BattleGround/BattleGround.h
src/game/BattleGround/BattleGroundMgr.cpp
src/game/BattleGround/BattleGroundMgr.h
src/modules/SD3/scripts/outland/auchindoun/mana_tombs/mana_tombs.cpp
src/modules/SD3/scripts/world/npcs_special.cpp
src/modules/SD3/system/ScriptLoader.cpp

Cmangos commit:
5078176 Check player exiting waiting area while starting battleground
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangosthree/server/99)

Check player exiting waiting area while starting battleground

---

src/modules/Eluna/UnitMethods.h
src/modules/SD3/base/escort_ai.cpp
src/modules/SD3/base/follower_ai.cpp
src/modules/SD3/base/pet_ai.cpp
src/modules/SD3/include/sc_creature.cpp
src/modules/SD3/scripts/eastern_kingdoms/burning_steppes.cpp
src/modules/SD3/scripts/kalimdor/the_barrens.cpp
src/modules/SD3/scripts/outland/auchindoun/sethekk_halls/boss_talon_king_ikiss.cpp

Correction made to function name
This bring Three inline with the other cores
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangosthree/server/101)

Correction made to function name

---

src/modules/SD3/include/sc_creature.cpp
src/modules/SD3/scripts/eastern_kingdoms/blackrock_mountain/blackrock_depths/blackrock_depths.cpp
src/modules/SD3/scripts/eastern_kingdoms/blackrock_mountain/molten_core/molten_core.cpp
src/modules/SD3/scripts/kalimdor/ruins_of_ahnqiraj/boss_moam.cpp
src/modules/SD3/scripts/northrend/borean_tundra.cpp
src/modules/SD3/scripts/outland/auchindoun/mana_tombs/mana_tombs.cpp
src/modules/SD3/scripts/outland/netherstorm.cpp
src/modules/SD3/scripts/outland/shadowmoon_valley.cpp

Script added - npc_kharan_mighthammer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangosthree/server/103)

Script added - npc_kharan_mighthammer

---

src/modules/SD3/system/ScriptLoader.cpp

Mana tombs added to ScriptLoader
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangosthree/server/104)

Mana tombs added to ScriptLoader

---

src/modules/SD3/system/ScriptLoader.cpp

AddSC_scholomance() added to ScriptLoader
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangosthree/server/105)

AddSC_scholomance() added to ScriptLoader

---

src/modules/SD3/scripts/eastern_kingdoms/blackrock_mountain/blackrock_depths/blackrock_depths.cpp
src/modules/SD3/scripts/eastern_kingdoms/blackrock_mountain/blackrock_depths/blackrock_depths.h
src/modules/SD3/scripts/eastern_kingdoms/blackrock_mountain/blackrock_depths/boss_emperor_dagran_thaurissan.cpp
src/modules/SD3/scripts/eastern_kingdoms/blackrock_mountain/blackrock_depths/boss_high_interrogator_gerstahn.cpp
src/modules/SD3/scripts/eastern_kingdoms/blackrock_mountain/blackrock_depths/instance_blackrock_depths.cpp

Core updated to use the latest version of ScriptDev3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangosthree/server/109)

Core updated to use the latest version of ScriptDev3

---

src/game/Object/Pet.cpp
src/game/Object/Pet.h
src/game/Object/PetAI.cpp
src/game/Object/Player.cpp
src/game/Object/Player.h
src/game/Object/SpellMgr.cpp
src/game/Object/SpellMgr.h
src/game/Object/Unit.cpp
src/game/Server/SharedDefines.h
src/game/WorldHandlers/Group.cpp
src/game/WorldHandlers/Group.h
src/game/WorldHandlers/PetHandler.cpp
src/game/WorldHandlers/QuestHandler.cpp
src/game/WorldHandlers/Spell.cpp
src/game/WorldHandlers/SpellAuras.cpp
src/game/WorldHandlers/SpellAuras.h
src/game/WorldHandlers/SpellEffects.cpp
src/game/WorldHandlers/UnitAuraProcHandler.cpp
src/game/WorldHandlers/World.cpp
src/mangosd/mangosd.conf.dist.in

I thankee, cmangos :-)
Commits:
13271d6 Commit Ported  Core Pet DB cleanup and simplification
60d6e29 Commit Imported  Core Utilize flags in PetAI (And uniform extra flags with the other cores)
06d30ce Commit Ported  Core Make pet assist owner on summon if not a passive
2821da8 Commit Ported  Core Fix Guardian reactions
4f88a9e Commit Ported  Core Pet AI Fixup
67e0558 Commit Imported  Core Fix pet unsummon on mount
f50041f Commit Imported  Core Fix player rooted after possesing an unit.
df59a93 Commit Imported  Core Syncing up pet work
056f4f5 Commit Imported  Core Fix a couple of invalid name for spell attributes
6a58f1f Commit Imported  Core only save correct auras on pet::SavePetToDB
34ab59b Commit Imported  Core Hunter summon pet (call pet) checkcast fixup
dfbb69c Commit Imported …

Cmangos Cata commits applied

---

src/game/WorldHandlers/GossipDef.cpp

Plus code tidied up, including the removal of unneccessary casts to
uint32.
Note: auto quest accept does not work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangosthree/server/116)

Displaying of the portait window fixed

---

src/shared/revision.h

Updated to World database revision 21 4 8

Updated to World database revision 21 4 8

---

src/game/Object/SpellMgr.cpp
src/game/WorldHandlers/SpellEffects.cpp

Updated to use the latest version of ScriptDev3
also added cmangos Cata commit:
https://github.com/cmangos/mangos-cata/commit/f061dbf
Thanks, cmangos :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangosthree/server/118)

Updated to use the latest version of ScriptDev3

---

src/game/Object/Object.cpp
src/game/Object/Object.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangosthree/server/121)

Fix Eluna crash.

---

src/tools/Extractor_projects/map-extractor/System.cpp
src/tools/Extractor_projects/shared/ExtractorCommon.h
src/tools/Extractor_projects/vmap-extractor/vmapexport.cpp

Not all required patch files were being applied during map and vmap
extraction/creation.
This fix has resulted in a few more (18) vmap files being created
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangosthree/server/123)

All required patch files are now being applied

---

src/tools/Extractor_projects/shared/ExtractorCommon.h
src/tools/Extractor_projects/vmap-extractor/vmapexport.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangosthree/server/129)

Fixed build
